{"status":{"code":500,"msg":"Traceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/tornado\/web.py\", line 1786, in _execute\n    result = await result\n  File \"\/code\/jigsaw\/handler\/app\/library.py\", line 14, in get\n    items, total = await LibraryService.get_library_items(\n  File \"\/code\/jigsaw\/service\/library.py\", line 148, in get_library_items\n    return await cls._get_library_items_cached(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/sealcn-0.2.0-py3.9.egg\/sealcn\/utils\/cache.py\", line 105, in __inner_wrapper__\n    data = await func(*args, **kwargs)\n  File \"\/code\/jigsaw\/service\/library.py\", line 46, in _get_library_items\n    items, total = await ABTestService.get_abtest_library_for_app(\n  File \"\/code\/jigsaw\/service\/abtest.py\", line 971, in get_abtest_library_for_app\n    return await cls._get_abtest_library_for_app_cached(\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/sealcn-0.2.0-py3.9.egg\/sealcn\/utils\/cache.py\", line 105, in __inner_wrapper__\n    data = await func(*args, **kwargs)\n  File \"\/code\/jigsaw\/service\/abtest.py\", line 1025, in _get_abtest_library_for_app\n    return await cls.query_library_for_app(\n  File \"\/code\/jigsaw\/service\/abtest.py\", line 1191, in query_library_for_app\n    await cursor.to_list(None), with_projection,\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/motor\/core.py\", line 1555, in _to_list\n    result = get_more_result.result()\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/motor\/core.py\", line 1758, in _on_started\n    pymongo_cursor = future.result()\n  File \"\/usr\/local\/lib\/python3.9\/concurrent\/futures\/thread.py\", line 52, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/pymongo\/collection.py\", line 2448, in aggregate\n    return self._aggregate(\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/pymongo\/_csot.py\", line 106, in csot_wrapper\n    return func(self, *args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/pymongo\/collection.py\", line 2355, in _aggregate\n    return self.__database.client._retryable_read(\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/pymongo\/_csot.py\", line 106, in csot_wrapper\n    return func(self, *args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/pymongo\/mongo_client.py\", line 1465, in _retryable_read\n    return func(session, server, sock_info, read_pref)\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/pymongo\/aggregation.py\", line 142, in get_cursor\n    result = sock_info.command(\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/pymongo\/helpers.py\", line 279, in inner\n    return func(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/pymongo\/pool.py\", line 879, in command\n    return command(\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/pymongo\/network.py\", line 166, in command\n    helpers._check_command_response(\n  File \"\/usr\/local\/lib\/python3.9\/site-packages\/pymongo\/helpers.py\", line 194, in _check_command_response\n    raise OperationFailure(errmsg, code, response, max_wire_version)\npymongo.errors.OperationFailure: Argument to $skip cannot be negative, full error: {'operationTime': Timestamp(1701960936, 1), 'ok': 0.0, 'errmsg': 'Argument to $skip cannot be negative', 'code': 15956, 'codeName': 'Location15956', '$clusterTime': {'clusterTime': Timestamp(1701960936, 1), 'signature': {'hash': b'\\xef\\x8a\\x8a,\\xc0\\x1b\\x05G5\\xb6\\xa5\\x8ce\\x1e\\xb0\\xe7\\xf7-\\x13\\xa5', 'keyId': 7273042523205926947}}}\n"}}